---
title: "Making RMarkdown Awesome"
subtitle: "Team Rocket"
author: "Ahmadou Dicko"
date: "2018-12-20"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

class: inverse middle center

<style>.red{color: red;} h3{text-align: center;} </style>

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
library(humicon)
```



# Easily insert web icons into RMarkdown

---

## Standard icons
--

* Get started

```{r}
humicon::hi("Agriculture")
```

--

* Playing with size

```{r}
humicon::hi("Deployment", size = 2)
```

--

* We can change color

```{r}
humicon::hi("Deployment", colour = "red", size = 5)
```

---

## Adding border


* Bigger than bigger

```{r}
humicon::hi("Livestock", colour = "red", size = 3, border = TRUE)
```

--

* Animating icons

```{r}
humicon::hi("Assessment", color = "steelblue", animate = "spin")
```


--

* Rotating icons

```{r}
humicon::hi("Sanitation", color = "brown", rotate = 90, size = 2)
```
